const TIMER_STATES = {
  SET: "SET",
  PENDING_STARTED: "PENDING_STARTED",
  STARTED: "STARTED",
  STOPPED: "STOPPED",
  PAUSED: "PAUSED",
  PENDING_FINISHED: "PENDING_FINISHED",
  FINISHED: "FINISHED",
};

export default TIMER_STATES;
